### ISSUE TITLE
Add some cool feature or improve something

### ISSUE THREAD

**Issue by cyruzin** [cyruzin/trailer#1]

**Comment by 0xsubi** [comment]
Added PR for showing Release Dates: https://github.com/cyruzin/trailer/pulls

Without release dates, it might be ambiguous to user as in which movie or show is being shown as there can be multiple movies / shows with the same name. 
This PR addresses this issue by showing US release dates for movies and first Aired dates for TV shows.

**Comment by cyruzin** [comment]
> Added PR for showing Release Dates: https://github.com/cyruzin/trailer/pulls
> 
> Without release dates, it might be ambiguous to user as in which movie or show is being shown as there can be multiple movies / shows with the same name.
> This PR addresses this issue by showing US release dates for movies and first Aired dates for TV shows.

Merged.
